[build]
  base    = "."
  command = "bash scripts/build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/zh/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200