server {
    listen 80;
    server_name dev-machine-society.boticz.com;

    root /usr/share/nginx/html;
    index index.html;

    # 中文版本
    location /zh/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /zh/index.html;
    }

    # 英文版本
    location /en/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /en/index.html;
    }
}